import type { Metadata } from "next";
import { headers } from "next/headers";
import { cookieToInitialState } from "wagmi";
import { Web3ModalProvider } from "@/contexts";
import { wagmiConfig } from "@/config";
import { Providers } from "./providers";

import "./globals.css";

export const metadata: Metadata = {
  title: "Unidocs",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  const initialState = cookieToInitialState(
    wagmiConfig,
    headers().get("cookie")
  );

  return (
    <html lang="en">
      <body className="min-h-screen bg-background antialiased">
        <Web3ModalProvider initialState={initialState}>
          <Providers>{children}</Providers>
        </Web3ModalProvider>
      </body>
    </html>
  );
};

export default RootLayout;
